# Generated by Django 4.2 on 2023-05-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participanthackathon',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/hackathon_submissions/file/'),
        ),
        migrations.AlterField(
            model_name='participanthackathon',
            name='submission_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/hackathon_submissions/image/'),
        ),
    ]
