# Generated by Django 4.2 on 2023-05-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_alter_participanthackathon_submission_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participanthackathon',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='media/hackathon_submissions/file/'),
        ),
        migrations.AlterField(
            model_name='participanthackathon',
            name='submission_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/hackathon_submissions/image/'),
        ),
    ]
