# Generated by Django 4.2 on 2023-05-11 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackathon', '0006_participant_hackathon_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='hackathon_submissions/file/')),
                ('submission_image', models.ImageField(blank=True, null=True, upload_to='hackathon_submissions/image/')),
                ('submission_link', models.URLField(blank=True, null=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.hackathon')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.participant')),
            ],
        ),
    ]
